CREATE TABLE products (
sl INT NOT NULL AUTO_INCREMENT,
id VARCHAR(4) NOT NULL,
title VARCHAR(30) NOT NULL,
main_category VARCHAR(30) NOT NULL,
sub_category VARCHAR(30) NOT NULL,
discount VARCHAR(2) NOT NULL,
price VARCHAR(4) NOT NULL,
rating VARCHAR(1) NOT NULL,
added_by VARCHAR(200) NOT NULL,
added_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (sl)
)


CREATE TABLE users (
id INT NOT NULL AUTO_INCREMENT,
frist_name VARCHAR(80) NOT NULL,
last_name VARCHAR(80) NOT NULL,
email VARCHAR(80) NOT NULL,
city VARCHAR(80) NOT NULL,
post VARCHAR(80) NOT NULL,
full_address VARCHAR(200) NOT NULL,
password VARCHAR(200) NOT NULL,
registered_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (id)
)

CREATE TABLE orders (
id INT NOT NULL AUTO_INCREMENT,
product_id VARCHAR(80) NOT NULL,
price VARCHAR(30) NOT NULL,
order_status VARCHAR(30) NOT NULL,
ispaid VARCHAR(30) NOT NULL,
ordered_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
customer_id INT(80) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (customer_id) REFERENCES users (id)
)

SELECT email, frist_name, city, post, product_id, price, ispaid FROM users JOIN orders ON users.id = orders.customer_id